### ISSUE TITLE
Grouping not working in .bat files

### ISSUE THREAD

**Issue by FGameCZ** [LaurenceRawlings/savify#10]
* Savify version: v2.0.10
* Python version: 3.9.0
* Operating System: Windows 10

### Description

I tried to make a .bat file to make downloading easier, but it didn't work.

### I made a .bat file looking like this:
 
```
@ECHO OFF
echo Please paste the song link
set/p "link=> "
cd C:/savify-dl
savify "link" -q best -f mp3 -g "%artist%/%album%" -o "C:\Users\xxx\Music\Spotify"
pause

And I got this error:
Error: Invalid value for '-g' / '--group': Group must be in the form x or x/x/x... where x in [%artist%, %album%, %playlist%]
```
### Thanks

**Comment by alexandrus21a** [comment]
### Hi, i have a same problem and delete from code % 
`if /i "%envrimet%" == "2" savify  "%url%" -q 192k -f mp3 -o "D:/ЗАГРУЗКИ/ytmdl" -g "artist/album" `
and work for me. I think author fix this problem

**Comment by FGameCZ** [comment]
> ### Hi, i have a same problem and delete from code %
> `if /i "%envrimet%" == "2" savify "%url%" -q 192k -f mp3 -o "D:/ЗАГРУЗКИ/ytmdl" -g "artist/album" `
> and work for me. I think author fix this problem

Hi, thank you for answering me, but deleting "%" from code doesn't work for me.

**Comment by alexandrus21a** [comment]
> > ### Hi, i have a same problem and delete from code %
> > `if /i "%envrimet%" == "2" savify "%url%" -q 192k -f mp3 -o "D:/ЗАГРУЗКИ/ytmdl" -g "artist/album" `
> > and work for me. I think author fix this problem
> 
> Hi, thank you for answering me, but deleting "%" from code doesn't work for me.
### Hi, maybe I forgot to say where to remove%
you need to open this file
\path-to-python\Lib\site-packages\savify\
and open the cli.py and change line 32
`regex = r"^((artist|album|%playlist%)(\/(artist|album|%playlist%))*)+$"`
If you want to download song with playlist int bat use them
`regex = r"^((artist|album|playlist)(\/(artist|album|playlist))*)+$"`
Finally save file as cli.py and smile.

**Comment by FGameCZ** [comment]
Hi,
Thanks for replying me. It didn't work for me, but I think, that I know where is the problem. I am using savify.exe.

**Comment by FGameCZ** [comment]
I have tried using python version and it works! Thank you.

**Comment by FGameCZ** [comment]
Sorry, but I just thought it is working. It just downloaded songs to folder "album" in folder "artist". Any other ideas?

**Comment by LaurenceRawlings** [comment]
I'm not sure which version you were using but this has been fixed in the latest version. The problem was that the %'s were missing, not that they should've been removed. Feel free to reopen if this is still an issue for you.
