### ISSUE TITLE
2 issue with savify

### ISSUE THREAD

**Issue by cisko99za** [LaurenceRawlings/savify#11]
* Savify version: latest
* Python version: 3.8.1
* Operating System: win 7 x64

### Description

Savify.exe not work on win 7 x64. api-ms-win-core-path-l1-1-0.dll is required. download and put dll on system32 not work.
work with python but have error with API credentials to environment. how to add?

**Comment by cisko99za** [comment]
add API credentials to my system but no work....

**Comment by LaurenceRawlings** [comment]
I the EXE is not working please use the python package for your system. During development I will only be targeting WIN10.
