### ISSUE TITLE
Bug "YouTube said: Unable to extract video data" - Savify.exe

### ISSUE THREAD

**Issue by FGameCZ** [LaurenceRawlings/savify#13]
* Savify version: v2.0.10
* Python version: 3.9.0
* Operating System: Windows 10 Home 20H2 64-bit

### Description

```
I wanted to download a song, but an error appeard.
```

### What I Did

```
savify "https://open.spotify.com/track/2FY7b99s15jUprqC0M5NCT" -q best -f mp3 -g "%artist%/%album%" -o "C:\Users\xxx\Music\Spotify".
```
```
[ERROR] ERROR: 9BPfyhhv7-c: YouTube said: Unable to extract video data
```
### Thanks

**Comment by FGameCZ** [comment]
I have tried using python version instead of .exe version and it works.

**Comment by LaurenceRawlings** [comment]
Issue was that youtubedl needed updating. Solved in the latest version.
