### ISSUE TITLE
Mention that Mp3s ared downloaded from youtube and not from spotify.

### ISSUE THREAD

**Issue by ehmkah** [LaurenceRawlings/savify#15]
* Savify version:2.0.10
* Python version:3.8
* Operating System: Linux

### Description

Would be nice to mention in the docs that savify downloads the mp3 from youtube and not from spotify. Only metainformation are used from spotify. So everybody understands that nothing illegal happens.  

Instead of this small issue, a nice library. 

### What I Did

Nothing - I learned new tool `mkvirtualenv` :-D

**Comment by LaurenceRawlings** [comment]
Added clarity to the README to clear up any confusion
