### ISSUE TITLE
Microsoft Defender - Trojan Alert

### ISSUE THREAD

**Issue by checkso** [LaurenceRawlings/savify#17]
* Savify version: v2.1.2
* Python version:
* Operating System: Windows 10

### Description

Just downloaded the latest version v2.1.2. 
Microsoft Defender blocks execution of savify.exe with the following:

Trojan:Script/Conteban.A!ml

### What I Did

executed savify.exe

**Comment by LaurenceRawlings** [comment]
I believe this can happen as I do not sign the assembly. Also when I make a new build Windows detects that it has not been run on many systems before as the signature changes. I can assure you Savify is not malicious in any way. The EXE is compiled straight from the source code using pyinstaller. Feel free to look through the code and maye run the EXE in a sandbox if you are still wary. Let me know if you have any other questions and maybe join the Discord to talk to others that have been using Savify.
