### ISSUE TITLE
[BUG] Logs won't show (Docker)

### ISSUE THREAD

**Issue by lucanello** [LaurenceRawlings/savify#22]
**Describe the bug**
The basic Docker implementation doesn't show logs when downloading songs. When terminating the program it suddenly prints the log.

**To Reproduce**
Use the following Dockerfile to build and run the container: https://gist.github.com/lucanello/31b641a9b8a43e474e95137602307120

**Expected behavior**
Savify should output to log as normal.

**Desktop (please complete the following information):**
 - OS: Docker
 - Version: 2.3.3

**Comment by LaurenceRawlings** [comment]
This is now fixed with the latest logger updates.
