### ISSUE TITLE
Installation Trouble

### ISSUE THREAD

**Issue by TiPunch69** [LaurenceRawlings/savify#3]
* Savify version: 2.0.5
* Python version: 3.9
* Operating System: Windows 10

### Description

I tried to follow the installation instructions, but failed. 

- Installed FFMpeg Version as in the instruction
- Downloaded savify.exe and run it via the command line. Got the error: `Cannot open C:\Own\Savify-script.py`

**Comment by LaurenceRawlings** [comment]
If you download the latest release this should now be fixed. All scripts are now bundled into the executable.
