### ISSUE TITLE
Bug : Fails to download because fail save the artwork

### ISSUE THREAD

**Issue by AIAficionado** [LaurenceRawlings/savify#4]
* Savify version:
* Python version: 3.7
* Operating System: Windows OS

### Description

It downloads the .mp3 file successfully but fails to save the cover image later on so deletes the file completely there should be an option or arg parse statment to not download cover images to avoid this 

Update: when I download the playlist for the same track the artwork gets downloaded sucessfully but get the same error messages 
"Failed to add artwork" then it deletes all the files

### What I Did
```
>>> from savify import Savify
>>> s = Savify(api_credentials=("user","pass"))
>>> s.download("https://open.spotify.com/track/1feANd8EfcDP5UqSvbheM3")
```

[DEBUG] [download] Downloading playlist: Sachet Tandon - Bekhayali (From "Kabir Singh") (AUDIO)
[DEBUG] [youtube:search] query "Sachet Tandon - Bekhayali (From "Kabir Singh") (AUDIO)": Downloading page 1
[DEBUG] [youtube:search] playlist Sachet Tandon - Bekhayali (From "Kabir Singh") (AUDIO): Downloading 1 videos
[DEBUG] [download] Downloading video 1 of 1
[DEBUG] [youtube] K9w6UBZOn5o: Downloading webpage
[DEBUG] [youtube] Downloading just video K9w6UBZOn5o because of --no-playlist
[DEBUG] [download] Destination: C:\Users\******\AppData\Roaming\Savify\temp\c5008e90-250e-11eb-905b-7c2a3178fa13.webm
[download]   0.0% of 6.05MiB at 14.71KiB/s ETA 07:01
[download]   0.0% of 6.05MiB at 42.86KiB/s ETA 02:24
[download]   0.1% of 6.05MiB at 95.89KiB/s ETA 01:04
[download]   0.2% of 6.05MiB at 200.00KiB/s ETA 00:31
[download]   0.5% of 6.05MiB at 313.13KiB/s ETA 00:19
[download]   1.0% of 6.05MiB at 459.85KiB/s ETA 00:13
[download]   2.0% of 6.05MiB at 404.46KiB/s ETA 00:15
[download]   4.1% of 6.05MiB at 537.97KiB/s ETA 00:11
[download]   8.2% of 6.05MiB at 541.31KiB/s ETA 00:10
[download]  16.5% of 6.05MiB at 579.60KiB/s ETA 00:08
[download]  26.6% of 6.05MiB at 643.97KiB/s ETA 00:07
[download]  39.3% of 6.05MiB at 717.79KiB/s ETA 00:05
[download]  54.5% of 6.05MiB at 790.96KiB/s ETA 00:03
[download]  71.8% of 6.05MiB at 815.21KiB/s ETA 00:02
[download]  86.4% of 6.05MiB at 823.85KiB/s ETA 00:01
[download] 100.0% of 6.05MiB at 870.56KiB/s ETA 00:00
[download] 100% of 6.05MiB in 00:07
[DEBUG] [ffmpeg] Destination: C:\Users\rlalchan\AppData\Roaming\Savify\temp\c5008e90-250e-11eb-905b-7c2a3178fa13.mp3
[DEBUG] Deleting original file C:\Users\rlalchan\AppData\Roaming\Savify\temp\c5008e90-250e-11eb-905b-7c2a3178fa13.webm (pass -k to keep)
[DEBUG] [download] Finished downloading playlist: Sachet Tandon - Bekhayali (From "Kabir Singh") (AUDIO)

Download Finished!
Completed 0/1 tracks in 40.2420s

Failed Tracks:

Track: Bekhayali (From "Kabir Singh")
Reason: Failed to add cover art.

**Comment by xXluki98Xx** [comment]
The same happend if you set the typ to flac.

**Comment by armagg** [comment]
same problem here :/

**Comment by djbigsmoke** [comment]
exact same problem, also when downloading a playlist

**Comment by LaurenceRawlings** [comment]
Released a patch that should fix this. Failed downloads are retried and failed artwork is skipped. Please test again and open another issue if the problem persists.
