### ISSUE TITLE
Savify not downloading songs

### ISSUE THREAD

**Issue by Aleandr-1987** [LaurenceRawlings/savify#40]
Hi, I followed all the instructions and installed savify. At first, it worked and downloaded songs for Spotify but suddenly it detects the songs list but doesn't download anything. It stuck with the downloading screen.
![Annotation 2021-02-08 123634](https://user-images.githubusercontent.com/66353026/107186449-513b7380-6a0a-11eb-972d-b2c40d7cca7d.png)

**Comment by LaurenceRawlings** [comment]
If the problem persists could you run the command with `-vv` and send the output. Alternatively you can check the log saved at `%appdata%/Savify/logs` by default.
