### ISSUE TITLE
[BUG] no such option: -m

### ISSUE THREAD

**Issue by haizz94** [LaurenceRawlings/savify#45]
If I use the template config from [docker-scripts/template.config.sh](https://github.com/LaurenceRawlings/savify/blob/main/docker-scripts/template.config.sh) for bulk download, the command fails with 

**no such option: -m**

When I remove the additional options Savify is working, but I want to create a playlist from the downloaded files. Which option do I have to use? I am using the docker version.

**Comment by lucanello** [comment]
Sorry for the late reply, you have to build the Docker image yourself: `docker build -t savify .`
The official Docker image is outdated right now.
