### ISSUE TITLE
Feature Request: Download complete Playlist

### ISSUE THREAD

**Issue by xXluki98Xx** [LaurenceRawlings/savify#5]
* Savify version: 2.0.7
* Python version: 3.7.3
* Operating System: Windows WSL2 / Debian, MacOS

### Description

As a User, i would like to download a whole playlist with more than 50 titles. It seems that Spotify has limited the view to 50 titles, so only the first 50 can be downloaded. 
At least one possibility to add an offset would be good.

**Comment by LaurenceRawlings** [comment]
This issue had already been patched. PLaylists bigger than 100 songs should now download with the latest version of Savify.
