### ISSUE TITLE
Env. Var is invaild

### ISSUE THREAD

**Issue by EXStevens** [LaurenceRawlings/savify#60]
I added the env var but it still shows "Spotify API credentials not setup!".

**Comment by EXStevens** [comment]
Well, it doesn't work in Windows. But works well in Linux

**Comment by ancestrychanged** [comment]
Nope, it works on windows. Here's what I did:
1) Open up cmd as admin
2) Locate the folder where Savify.exe is at
3) Do things with Savify.exe in the cmd
4) Profit

**Comment by EXStevens** [comment]
Thank you for your solution 😊.
But I'm using Tidal now, tidal-dl is great 😃.
