### ISSUE TITLE
Can not change the quality of mp3

### ISSUE THREAD

**Issue by elox92** [LaurenceRawlings/savify#7]
* Savify version: 2.0.7
* Python version:3.8.2
* Operating System: windows 10

### Description
When trying to download mp3 and use a custom quality I get and int() error. 
Only when use quality=Quality.BEST I get the mp3 without error, but the bitrate is 124kbps in all the mp3 songs.

### What I Did

>>> s = Savify(api_credentials=("user","pass"), download_format='mp3', quality=Quality.Q256K, output_path=Path(C:\Users\name\Desktop), group='%album%')
>>> s.download(link)

ERROR: invalid literal for int() with base 10: '256K'

**Comment by LaurenceRawlings** [comment]
Thanks for pointing this out, I am trying to find the problem and will do my best to fix soon.

**Comment by LaurenceRawlings** [comment]
Fixed in the latest release.

**Comment by elox92** [comment]
Thanks for the fix
