### ISSUE TITLE
[BUG] Downloads don't go to current dir

### ISSUE THREAD

**Issue by v1ctorio** [LaurenceRawlings/savify#94]
**Describe the bug**
I don't know where downloads go by default, they don't go to current directory, I don't know if this is expected behaviour but it isn't specified on the README

**To Reproduce**
- `savify "<spotify playlist dir>"`
- A .cache file is created on current directory but nothing else, command output is completley normal 

**Expected behavior**
- Songs being downloaded on current directory

**Screenshots**
![output](https://github.com/LaurenceRawlings/savify/assets/74506415/2aed69bb-d246-4f17-b62b-e2e947d41557)
**Desktop**
 - OS: manjaro
 - Version [2.4.0]

**Additional context**
- using zsh 
- Installed using `pipx`

**Comment by bleov** [comment]
From the README:

![image](https://github.com/LaurenceRawlings/savify/assets/48164825/92b93f83-2857-45b1-af4b-791c277a6679)

**Comment by v1ctorio** [comment]
I'm just dumb, sorry.
